"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { LogIn, LogOut } from "lucide-react";
import { useState } from "react";
import { Badge, Button, Card, EmptyState, Input, PageHeader } from "@/components/ui";
import { invokeEdge } from "@/lib/api/edge";
import { createClient } from "@/lib/supabase/client";

export function AttendanceView(){
 const [identifier,setIdentifier]=useState("");const [notice,setNotice]=useState<{ok:boolean;text:string}|null>(null);const qc=useQueryClient();const today=new Date();today.setHours(0,0,0,0);
 const list=useQuery({queryKey:["attendance",today.toISOString().slice(0,10)],queryFn:async()=>{const {data,error}=await createClient().from("attendances").select("id,check_in,check_out,minutes_stayed,result,denied_reason,members(code,first_name,last_name)").gte("check_in",today.toISOString()).order("check_in",{ascending:false}).limit(100);if(error)throw error;return data;}});
 const checkin=useMutation({mutationFn:()=>invokeEdge<{allowed:boolean}>("attendance-check-in",{identifier,method:"manual"}),onSuccess:r=>{setNotice({ok:Boolean(r.data?.allowed),text:r.message});setIdentifier("");qc.invalidateQueries({queryKey:["attendance"]});qc.invalidateQueries({queryKey:["dashboard"]});},onError:e=>{setNotice({ok:false,text:e.message});qc.invalidateQueries({queryKey:["attendance"]});}});
 const checkout=useMutation({mutationFn:(id:string)=>invokeEdge("attendance-check-out",{attendance_id:id}),onSuccess:r=>{setNotice({ok:true,text:r.message});qc.invalidateQueries({queryKey:["attendance"]});}});
 const allowed=list.data?.filter((a:any)=>a.result==='permitido').length??0;const inside=list.data?.filter((a:any)=>a.result==='permitido'&&!a.check_out).length??0;const denied=list.data?.filter((a:any)=>a.result==='denegado').length??0;
 return <><PageHeader title="Control de asistencia" description="Valida el acceso por código o documento del socio."/><div className="grid gap-6 xl:grid-cols-[.7fr_1.3fr]"><div><Card className="bg-carbon text-white"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-brand"><LogIn/></div><h2 className="mt-6 text-2xl font-black">Registrar ingreso</h2><p className="mt-2 text-sm text-slate-400">El sistema verifica estado, vigencia, saldo, sesiones y horario.</p><form onSubmit={e=>{e.preventDefault();setNotice(null);checkin.mutate()}} className="mt-7"><Input autoFocus required value={identifier} onChange={e=>setIdentifier(e.target.value)} placeholder="Código o documento" className="h-14 border-white/10 bg-white/10 text-lg font-bold text-white placeholder:text-slate-500"/><Button disabled={checkin.isPending} className="mt-3 h-12 w-full">{checkin.isPending?"Validando…":"Permitir ingreso"}</Button></form>{notice&&<p className={`mt-4 rounded-xl p-3 text-sm ${notice.ok?"bg-emerald-500/15 text-emerald-300":"bg-red-500/15 text-red-300"}`}>{notice.text}</p>}</Card><div className="mt-4 grid grid-cols-3 gap-3">{[["Ingresos",allowed],["Dentro",inside],["Denegados",denied]].map(([l,v])=><Card key={l} className="p-4 text-center"><p className="text-2xl font-black">{v}</p><p className="text-xs text-slate-500">{l}</p></Card>)}</div></div><div>{list.data?.length?<Card className="overflow-hidden p-0"><div className="border-b border-slate-100 px-5 py-4 font-black">Actividad de hoy</div><div className="divide-y divide-slate-100">{list.data.map((a:any)=><div key={a.id} className="flex items-center justify-between gap-4 px-5 py-4"><div><p className="font-bold">{a.members?.first_name} {a.members?.last_name}</p><p className="text-xs text-slate-400">{a.members?.code} · {new Date(a.check_in).toLocaleTimeString("es-PE",{hour:"2-digit",minute:"2-digit"})}{a.denied_reason?` · ${a.denied_reason}`:""}</p></div><div className="flex items-center gap-3"><Badge className={a.result==='permitido'?"bg-emerald-50 text-emerald-700":"bg-red-50 text-red-700"}>{a.result}</Badge>{a.result==='permitido'&&!a.check_out&&<button onClick={()=>checkout.mutate(a.id)} title="Registrar salida" className="grid h-9 w-9 place-items-center rounded-lg bg-slate-100 text-slate-600"><LogOut size={16}/></button>}</div></div>)}</div></Card>:<EmptyState>{list.isLoading?"Cargando actividad…":"Aún no hay registros hoy."}</EmptyState>}</div></div></>;
}
