"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Plus, Search } from "lucide-react";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { Badge, Button, Card, EmptyState, Input, PageHeader } from "@/components/ui";
import { createClient } from "@/lib/supabase/client";
import type { Member } from "@/lib/types";

const schema = z.object({ first_name:z.string().min(2,"Ingresa el nombre"), last_name:z.string().min(2,"Ingresa el apellido"), document_number:z.string().optional(), phone:z.string().optional(), email:z.union([z.string().email("Correo inválido"),z.literal("")]) });
type Values=z.infer<typeof schema>;
const colors:Record<string,string>={activo:"bg-emerald-50 text-emerald-700",moroso:"bg-amber-50 text-amber-700",congelado:"bg-cyan-50 text-cyan-700",inactivo:"bg-slate-100 text-slate-600",baja:"bg-red-50 text-red-700"};

export function MembersView(){
 const [q,setQ]=useState(""); const [show,setShow]=useState(false); const [editing,setEditing]=useState<Member|null>(null); const qc=useQueryClient();
 const query=useQuery({queryKey:["members",q],queryFn:async()=>{let req=createClient().from("members").select("id,code,first_name,last_name,document_number,phone,email,status,joined_at,photo_path").order("last_name").limit(100);if(q)req=req.or(`first_name.ilike.%${q}%,last_name.ilike.%${q}%,code.ilike.%${q}%,document_number.ilike.%${q}%,phone.ilike.%${q}%`);const {data,error}=await req;if(error)throw error;return data as Member[];}});
 const form=useForm<Values>({resolver:zodResolver(schema),defaultValues:{first_name:"",last_name:"",document_number:"",phone:"",email:""}});
 const save=useMutation({mutationFn:async(v:Values)=>{const payload={...v,email:v.email||null,document_number:v.document_number||null,phone:v.phone||null};const req=editing?createClient().from("members").update(payload).eq("id",editing.id):createClient().from("members").insert(payload);const {data,error}=await req.select().single();if(error)throw error;return data;},onSuccess:()=>{qc.invalidateQueries({queryKey:["members"]});setShow(false);setEditing(null);form.reset();}});
 const beginEdit=(m:Member)=>{setEditing(m);setShow(true);form.reset({first_name:m.first_name,last_name:m.last_name,document_number:m.document_number??"",phone:m.phone??"",email:m.email??""});window.scrollTo({top:0,behavior:"smooth"});};
 const beginNew=()=>{setEditing(null);form.reset();setShow(true)};
 return <><PageHeader title="Socios" description="Expedientes, estado y datos de contacto en un solo lugar."><Button onClick={beginNew}><Plus size={17} className="mr-2"/>Nuevo socio</Button></PageHeader>{show&&<Card className="mb-6"><form onSubmit={form.handleSubmit(v=>save.mutate(v))} className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><label className="text-xs font-bold text-slate-600">Nombre<Input className="mt-1" {...form.register("first_name")}/><span className="text-accent">{form.formState.errors.first_name?.message}</span></label><label className="text-xs font-bold text-slate-600">Apellido<Input className="mt-1" {...form.register("last_name")}/></label><label className="text-xs font-bold text-slate-600">Documento<Input className="mt-1" {...form.register("document_number")}/></label><label className="text-xs font-bold text-slate-600">Teléfono<Input className="mt-1" {...form.register("phone")}/></label><div className="flex items-end"><Button className="w-full" disabled={save.isPending}>{save.isPending?"Guardando…":editing?"Actualizar socio":"Guardar socio"}</Button></div>{save.error&&<p className="text-sm text-accent sm:col-span-2 xl:col-span-5">No se pudo guardar. Verifica que el documento o código no esté repetido.</p>}</form></Card>}<div className="mb-5 max-w-md"><div className="relative"><Search className="absolute left-3 top-3 text-slate-400" size={18}/><Input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar por nombre, código, documento o teléfono" className="pl-10"/></div></div>{query.data?.length?<Card className="overflow-hidden p-0"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-4">Socio</th><th className="px-5 py-4">Documento</th><th className="px-5 py-4">Contacto</th><th className="px-5 py-4">Estado</th><th/></tr></thead><tbody className="divide-y divide-slate-100">{query.data.map(m=><tr key={m.id} className="hover:bg-slate-50"><td className="px-5 py-4"><p className="font-bold text-carbon">{m.first_name} {m.last_name}</p><p className="text-xs text-slate-400">{m.code}</p></td><td className="px-5 py-4 text-slate-600">{m.document_number||"—"}</td><td className="px-5 py-4"><p>{m.phone||"—"}</p><p className="text-xs text-slate-400">{m.email}</p></td><td className="px-5 py-4"><Badge className={colors[m.status]}>{m.status}</Badge></td><td className="px-5 py-4 text-right"><button onClick={()=>beginEdit(m)} className="text-xs font-bold text-brand">Editar</button></td></tr>)}</tbody></table></div></Card>:<EmptyState>{query.isLoading?"Cargando socios…":"No hay socios que coincidan con la búsqueda."}</EmptyState>}</>;
}
